=== lilonpro/mapForce_poc/household.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/object_02",
  "definitions": {
    "object_01": {
      "title": "client",
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "dob"
      ],
      "additionalProperties": false,
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "dob": {
          "type": "string"
        },
        "offset": {
          "type": "number"
        },
        "type": {
          "type": "string"
        },
        "relationships": {
          "type": "array",
          "title": "relationships",
          "items": {
            "$ref": "#/definitions/object_01"
          }
        }
      }
    },
    "object_02": {
      "type": "object",
      "required": [
        "client",
        "retirementDate",
        "plans",
        "assets"
      ],
      "additionalProperties": false,
      "properties": {
        "client": {
          "$ref": "#/definitions/object_01"
        },
        "retirementDate": {
          "type": "string"
        },
        "plans": {
          "type": "array",
          "title": "plans",
          "items": {
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "assets": {
          "title": "assets",
          "type": "object",
          "required": [
            "cash",
            "stock",
            "insurance"
          ],
          "additionalProperties": false,
          "properties": {
            "cash": {
              "type": "number"
            },
            "stock": {
              "type": "number"
            },
            "insurance": {
              "type": "number"
            }
          }
        }
      }
    }
  }
}

=== lilonpro/mapForce_poc/household.json
{
	"client": {
		"firstName": "James",
		"lastName": "Bond",
		"dob": "1949-10-01",
		"relationships": [
			{
				"firstName": "Jim",
				"lastName": "Bond",
				"dob": "1979-10-01",
				"offset": 1,
				"type": "son",
				"relationships": [
						{
						"firstName": "Jimmy",
						"lastName": "Bond",
						"dob": "2009-10-01",
						"offset": 1,
						"type": "grandson"
					}
				]
			}
		]
	},
	"retirementDate": "2009-10-10",
	"plans": [
		{
			"id": "123",
			"name": "plan_0"
		},
		{
			"id": "234",
			"name": "plan_1"
		},
		{
			"id": "345",
			"name": "plan_2"
		}
	],
	"assets": {
		"cash": 100,
		"stock": 200,
		"insurance": 300
	}
}
